### ISSUE TITLE
Docker?

### ISSUE THREAD

**Issue by kylrth** [YoRyan/nuxhash#79]
It'd be cool if there were a Docker image. Then for GPU setups it'd be as easy as using the nvidia container runtime with docker-compose.

**Comment by metajiji** [comment]
This is simple, just try this

```dockerfile
FROM python:3

WORKDIR /nuxhash

ENV PATH=/nuxhash/venv/bin:$PATH

ENV NUXHASH_VERSION=v1.0.0b2
RUN python3 -m venv venv \
    && . venv/bin/activate \
    && pip install --no-cache-dir \
        git+https://github.com/YoRyan/nuxhash@$NUXHASH_VERSION \
    && mkdir -p .config/nuxhash \
\
# Workaround and this should be fixed in code later
    && echo '{}' > benchmarks.json \
    && touch settings.conf
```

```yaml
---

version: '3.9'

services:
  nuxhash:
    build: .
    command: nuxhashd -c ./
```

```bash
docker-compose build
docker-compose run --rm nuxhash nuxhashd -c ./
docker-compose up -d
```
